version: "3.9"

services:

    front:
        build:
            context: .
            dockerfile: ./dockerfiles/front.Dockerfile
        image:
            bap/front

        
    back:
        build:
            context: .
            dockerfile: ./dockerfiles/back.Dockerfile
        image:
            bap/back
    
    admin:
        build:
            context: .
            dockerfile: ./dockerfiles/admin.Dockerfile
        image:
            bap/admin
    
    db:
        build:
            context: .
            dockerfile: ./dockerfiles/db.Dockerfile
        image:
            bap/db
